version: '3.8'

services:
  frontend:
    build: 
      context: ./app/todo-frontend
      dockerfile: Dockerfile
      # Remove the VITE_API_URL build arg as we're using relative URLs now
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
      
  backend:
    build: 
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Backend should reference itself for internal URLs
      - API_URL=http://backend:8000
      - DB_HOST=postgres  # This is correct - using service name
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - app-network  # Add network for container communication

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network  # Add network for container communication

# Define the network that allows containers to communicate
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: