
services:

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    
    environment:
      - BACKEND_URL=http://backend:8000  # Add this to configure nginx
    networks:
      - app-network
    depends_on:
      - backend
    ports:
      - "80:80"
    
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    
    environment:
      - DB_HOST=postgres
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
  
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Use named volume instead
    user: postgres  # Add this to fix permission issues
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:  # This is now being used