services:
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=${BACKEND_URL:-http://backend:8000}
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://backend:8000}
      - VITE_API_URL=/api
    networks:
      - app-network
    depends_on:
      - backend
    ports:
      - "80:80"
    
  backend:
    image: kaziiriad/todo-backend:dev_deploy
    environment:
      - DB_HOST=postgres
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
      
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
