version: '3'
services:
  backend:
    image: ${ECR_REPO_URL}:latest
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - REDIS_HOST=${REDIS_HOST}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"