config:
  aws:region: ap-southeast-1
  docker:username: kaziiriad
  docker:version: dev_deploy
  database:user: myuser
  database:password:
    secure: AAABALzfFYljYSxWduSvHNjKdRY5i8O3mD81UJ2cw9IcmTQnio20FYqd
  database:name: mydb
