---
bastion:
  hosts:
    bastion-1:
      ansible_host: 47.128.246.148
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/riadwsl/.ssh/MyKeyPair.pem
      ansible_ssh_common_args: -o StrictHostKeyChecking=no