---
db_masters:
  hosts:
    db_masters-1:
      ansible_host: 10.0.2.177
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/riadwsl/.ssh/MyKeyPair.pem
      ansible_ssh_common_args: '-o ProxyCommand="ssh -i /home/riadwsl/.ssh/MyKeyPair.pem -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ConnectionAttempts=5 -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -W %h:%p ubuntu@13.212.60.22"'

db_replicas:
  hosts:
    db_replicas-1:
      ansible_host: 10.0.4.185
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/riadwsl/.ssh/MyKeyPair.pem
      ansible_ssh_common_args: '-o ProxyCommand="ssh -i /home/riadwsl/.ssh/MyKeyPair.pem -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ConnectionAttempts=5 -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -W %h:%p ubuntu@13.212.60.22"'
    db_replicas-2:
      ansible_host: 10.0.6.222
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/riadwsl/.ssh/MyKeyPair.pem
      ansible_ssh_common_args: '-o ProxyCommand="ssh -i /home/riadwsl/.ssh/MyKeyPair.pem -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ConnectionAttempts=5 -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -W %h:%p ubuntu@13.212.60.22"'

database_servers:
  children:
    db_masters:
    db_replicas:
